apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: mysql-service
  name: mysql-service
spec:
  ports:
  - name: 3308-3306
    port: 3308
    protocol: TCP
    targetPort: 3306
    nodePort: 30308
  selector:
    app: mysql
  type: NodePort
status:
  loadBalancer: {}
